// Custom Worker entrypoint (OpenNext custom-worker pattern):
// https://opennext.js.org/cloudflare/howtos/custom-worker
//
// Re-exports the generated OpenNext `fetch` handler (+ its Durable Objects) and
// adds a `scheduled()` handler so Cloudflare Cron Triggers run our background
// jobs IN-WORKER. That removes the failure mode of the old GitHub Actions crons
// (an HTTP round-trip authorised by a separately-managed CRON_SECRET that drifted
// out of sync with the deployment): here the cron route is invoked in-process via
// the same fetch pipeline, self-authenticated with the Worker's own CRON_SECRET.

// `.open-next/worker.js` is generated by `opennextjs-cloudflare build` AFTER
// `next build` and is gitignored, so it's absent at type-check time on a clean
// tree. @ts-ignore is required (not @ts-expect-error, which would itself error on
// the builds where the file IS present). The disable is scoped to the two
// generated-import lines of the documented OpenNext custom-worker pattern.
/* eslint-disable @typescript-eslint/ban-ts-comment */
// @ts-ignore
import { default as handler } from './.open-next/worker.js';

// @ts-ignore
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from './.open-next/worker.js';
/* eslint-enable @typescript-eslint/ban-ts-comment */

// Cron string (must match wrangler `triggers.crons`) -> /api/cron/<name> route(s).
// notify runs every minute for tight session-relative reminders; the rest keep
// the cadence they had as GitHub Actions workflows.
const CRON_JOBS: Record<string, string[]> = {
  '* * * * *': ['notify'],
  '*/10 * * * *': ['warm-sessions'],
  '*/15 * * * *': ['publish-posts'],
  '*/30 * * * *': ['warm-results'],
  '7,22,37,52 * * * *': ['news'],
  '0 * * * *': ['betting-notify'],
  '47 */3 * * *': ['settle-markets'],
  '17 */6 * * *': ['health'],
  '29 */12 * * *': ['open-markets'],
  '41 4 * * *': ['grant-credits'],
  '19 5 * * *': ['award-prizes'],
  '0 8 * * 1': ['race-week'],
  '20 6 * * 2': ['recheck-results'],
};

type Ctx = { waitUntil(p: Promise<unknown>): void };

const workerHandler = {
  fetch: handler.fetch,
  async scheduled(event: { cron: string }, env: { CRON_SECRET?: string }, ctx: Ctx): Promise<void> {
    const jobs = CRON_JOBS[event.cron] ?? [];
    for (const job of jobs) {
      // Self-request over HTTPS to the public route (needs global_fetch_strictly_public
      // so the Worker can reach its own zone). Auth = the Worker's own CRON_SECRET,
      // so it always matches the route's check — no external secret to keep in sync.
      ctx.waitUntil(
        fetch(`https://paddock-tracker.com/api/cron/${job}`, {
          headers: env.CRON_SECRET ? { Authorization: `Bearer ${env.CRON_SECRET}` } : {},
        })
          .then((r: Response) => console.log(`[cron] ${job} -> ${r.status}`))
          .catch((e: unknown) => console.error(`[cron] ${job} failed:`, e)),
      );
    }
  },
};
