// Build the openGraph + twitter blocks for per-route Metadata.
//
// Next 16's Metadata API does NOT deep-merge openGraph + twitter blocks —
// page-level returns fully replace the layout's matching block. If a page
// returns only { title, description } from generateMetadata, the root's
// openGraph + twitter blocks win (so every social share preview reads the
// homepage copy). If a page returns openGraph: { title, description } without
// setting type / url / siteName, those three fields are lost. Same for
// twitter.card.
//
// This helper re-sets every field that needs to survive the no-deep-merge
// override. siteName + default type live here as constants; url is required
// per-route (the layout's root URL is wrong on every non-home page).

import type { Metadata } from 'next';
import { SITE_TITLE, SITE_URL } from './site';

/** The branded share card generated by `app/opengraph-image.tsx` and served at
 *  the static `/opengraph-image` route.
 *
 *  ABSOLUTE, not relative. A relative URL is resolved against `metadataBase`,
 *  which the three group layouts set — but `app/not-found.tsx` sits outside all
 *  of them, so its card resolved to `http://localhost:3000/opengraph-image` in
 *  the prerendered 404. An absolute URL cannot be resolved wrongly by any route,
 *  with or without a metadataBase, which removes the whole class of fault rather
 *  than patching the one page that hit it.
 *
 *  Three consumers: both group layouts (for routes that declare no openGraph of
 *  their own) and `withSocialMeta` below. One definition because a share card
 *  that differs between the layout and the page is worse than none. */
export const SOCIAL_CARD = [
  { url: `${SITE_URL}/opengraph-image`, width: 1200, height: 630, alt: SITE_TITLE },
];

export function withSocialMeta(args: {
  title: string;
  description: string;
  /** Set on a route that ships its OWN `opengraph-image.tsx`, so the card is
   *  omitted here and the colocated file supplies it instead.
   *
   *  This is NOT belt-and-braces. Measured 2026-08-25: an explicit `images` in
   *  the metadata object BEATS the file convention, which is the opposite of
   *  what a comment in `app/(app)/blog/[slug]/page.tsx` asserts. Adding the
   *  card unconditionally replaced the weekend page's own generated card with
   *  the generic one — caught by checking each route type after the change
   *  rather than trusting the documented priority. */
  ownCard?: boolean;
  // Path relative to SITE_URL, e.g. "/series/f1". Optional — the og:url field
  // is best-effort; omitting it falls back to the layout's site root, which
  // is wrong but not catastrophic (Twitter / Facebook crawlers re-resolve from
  // the actual fetch URL anyway).
  path?: string;
  type?: 'website' | 'article';
}): Pick<Metadata, 'openGraph' | 'twitter'> {
  const type = args.type ?? 'website';
  // The branded share card, named EXPLICITLY.
  //
  // `app/opengraph-image.tsx` generates it and `/opengraph-image` serves it
  // (a static route), but until 0.334.37 nothing referenced it: the file
  // convention attaches an image only to the segment that HOLDS the file, and
  // every page on this site lives inside a route group — `(marketing)` for `/`,
  // `(app)` for the rest — so the root card was generated, served, and pointed
  // at by no page. Measured on prod: `/`, `/app`, `/calendar` and every series
  // page shipped with NO og:image at all, so every share of them rendered as a
  // bare text link, while the Worker carried ~618 KiB for the runtime producing
  // the card nobody saw.
  //
  // Setting it here rather than adding `opengraph-image.tsx` files per group,
  // because a copy inside a route group resolves to the SAME `/opengraph-image`
  // URL as the root file and collides. Relative path resolves against the
  // `metadataBase` each group layout sets.
  //
  // Routes with their OWN colocated card pass `ownCard` and are skipped here —
  // see the note on that option; the documented file-based priority does NOT
  // hold for images.
  const card = args.ownCard ? {} : { images: SOCIAL_CARD };
  return {
    openGraph: {
      type,
      title: args.title,
      description: args.description,
      siteName: SITE_TITLE,
      ...card,
      ...(args.path ? { url: `${SITE_URL}${args.path}` } : {}),
    },
    twitter: {
      card: 'summary_large_image',
      title: args.title,
      description: args.description,
      ...card,
    },
  };
}
