// Codegen: bundle every text file under content/** (+ repo-root RELEASES.md)
// into an importable TS module, so the Cloudflare Worker can read curated
// content WITHOUT runtime fs. Cloudflare's unenv Node shim doesn't implement
// fs.readFile/readdir for bundled files, so the site's fs-backed content
// loaders return empty on Workers. This manifest is imported (webpack inlines
// it) and read via lib/content-fs.ts. Regenerated in `prebuild`.
//
//   npx tsx scripts/bundle-content.mts
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import path from 'node:path';

const ROOT = process.cwd();
const OUT = path.join(ROOT, 'lib', 'content-bundle.generated.ts');
const TEXT_EXT = new Set(['.json', '.md', '.mdx', '.ics', '.txt', '.csv']);

const map: Record<string, string> = {};

function walk(dir: string): void {
  for (const name of readdirSync(dir)) {
    const full = path.join(dir, name);
    if (statSync(full).isDirectory()) {
      walk(full);
      continue;
    }
    if (!TEXT_EXT.has(path.extname(name).toLowerCase())) continue;
    // Key relative to the repo root, forward-slashed: "content/series/f1/meta.json".
    map[path.relative(ROOT, full).replace(/\\/g, '/')] = readFileSync(full, 'utf-8');
  }
}

walk(path.join(ROOT, 'content'));
// Repo-root text files read via fs by app code (the /changelog reader).
for (const extra of ['RELEASES.md']) {
  try {
    map[extra] = readFileSync(path.join(ROOT, extra), 'utf-8');
  } catch {
    /* absent — skip */
  }
}

const body = JSON.stringify(map);
const header =
  '// AUTO-GENERATED by scripts/bundle-content.mts — DO NOT EDIT.\n' +
  '// Bundles content/** (+ RELEASES.md) so the Cloudflare Worker reads curated\n' +
  '// content without runtime fs (unenv lacks fs.readFile/readdir on workerd).\n';
writeFileSync(OUT, `${header}export const CONTENT_BUNDLE: Record<string, string> = ${body};\n`);
console.error(
  `bundled ${Object.keys(map).length} files -> ${path.relative(ROOT, OUT)} (${(body.length / 1024 / 1024).toFixed(2)} MB)`,
);
