// Codegen: bundle every text file under content/** (+ repo-root RELEASES.md)
// into an importable TS module, so the Cloudflare Worker can read curated
// content WITHOUT runtime fs. Cloudflare's unenv Node shim doesn't implement
// fs.readFile/readdir for bundled files, so the site's fs-backed content
// loaders return empty on Workers. This manifest is imported (webpack inlines
// it) and read via lib/content-fs.ts. Regenerated in `prebuild`.
//
//   npx tsx scripts/bundle-content.mts
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import path from 'node:path';

const ROOT = process.cwd();
const OUT = path.join(ROOT, 'lib', 'content-bundle.generated.ts');
const TEXT_EXT = new Set(['.json', '.md', '.mdx', '.ics', '.txt', '.csv']);

const map: Record<string, string> = {};

function walk(dir: string): void {
  for (const name of readdirSync(dir)) {
    const full = path.join(dir, name);
    if (statSync(full).isDirectory()) {
      walk(full);
      continue;
    }
    if (!TEXT_EXT.has(path.extname(name).toLowerCase())) continue;
    // Key relative to the repo root, forward-slashed: "content/series/f1/meta.json".
    map[path.relative(ROOT, full).replace(/\\/g, '/')] = readFileSync(full, 'utf-8');
  }
}

walk(path.join(ROOT, 'content'));

// RELEASES.md is DELIBERATELY NOT BUNDLED, and this is load-bearing.
//
// It was the single largest entry here: 233 KB raw, ~76 KiB GZIPPED inside the
// Worker script, and the only file that grows on literally every push. Its one
// reader is /changelog, which is `export const dynamic = 'force-static'` with no
// revalidate — so `loadReleaseGroups` runs at BUILD time, in Node, where
// lib/content-fs.ts falls through a bundle miss to the real filesystem and reads
// it fine. The bytes never need to reach the runtime at all.
//
// ⚠ THE CONSTRAINT THAT KEEPS THIS TRUE: /changelog must stay build-time only.
// Give that route a `revalidate`, or make it dynamic, and it will try to read
// RELEASES.md on workerd, where unenv has no fs — `loadReleaseGroups` catches
// and returns [], so the page fail-softs to "Nothing here yet" rather than
// erroring. Quiet, not loud. If you need /changelog to revalidate, put this file
// back in the bundle in the same change.
const EXCLUDED_FROM_BUNDLE = ['RELEASES.md'];

const body = JSON.stringify(map);
const header =
  '// AUTO-GENERATED by scripts/bundle-content.mts — DO NOT EDIT.\n' +
  '// Bundles content/** so the Cloudflare Worker reads curated content without\n' +
  '// runtime fs (unenv lacks fs.readFile/readdir on workerd). RELEASES.md is\n' +
  '// deliberately EXCLUDED — see the note in the script.\n';
writeFileSync(OUT, `${header}export const CONTENT_BUNDLE: Record<string, string> = ${body};\n`);
console.error(
  `bundled ${Object.keys(map).length} files -> ${path.relative(ROOT, OUT)} (${(body.length / 1024 / 1024).toFixed(2)} MB)` +
    `; excluded: ${EXCLUDED_FROM_BUNDLE.join(', ')}`,
);
